CREATE TABLE "timetracker_work_day" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timetracker_work_day_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"weekId" integer NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"startTime" time NOT NULL,
	"endTime" time NOT NULL,
	"totalHours" integer NOT NULL,
	"isDayOff" boolean DEFAULT false NOT NULL,
	"isHoliday" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "timetracker_work_week" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timetracker_work_week_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"weekNumber" integer NOT NULL,
	"year" integer NOT NULL,
	"targetHours" integer NOT NULL,
	"breakDuration" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "timetracker_work_day" ADD CONSTRAINT "timetracker_work_day_weekId_timetracker_work_week_id_fk" FOREIGN KEY ("weekId") REFERENCES "public"."timetracker_work_week"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "week_day_idx" ON "timetracker_work_day" USING btree ("weekId","date");--> statement-breakpoint
CREATE INDEX "week_year_idx" ON "timetracker_work_week" USING btree ("weekNumber","year");