CREATE TABLE "timetracker_day_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timetracker_day_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dayName" varchar(20) NOT NULL,
	"defaultStartTime" time DEFAULT '09:00:00' NOT NULL,
	"defaultEndTime" time DEFAULT '17:00:00' NOT NULL,
	"defaultHours" integer DEFAULT 480 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "day_name_idx" ON "timetracker_day_settings" USING btree ("dayName");--> statement-breakpoint
ALTER TABLE "timetracker_work_day" DROP COLUMN "isHoliday";